language: pt
pipeline:
  - name: SpacyNLP # Load the largest lib avaliable of the spacy lib
    model: pt_core_news_lg # return the same word vector for lower case and the upper case.
    case_sensitive: False
  - name: SpacyTokenizer #Tokenizer using spaCy. Creates tokens using the spaCy tokenizer.
  - name: SpacyFeaturizer # Creates features for entity extraction, intent classification, and response classification using the spaCy featurizer.
  - name: DIETClassifier # Dual Intent Entity Transformer (DIET) used for intent classification and entity extraction.
    epochs: 55 # This parameter sets the number of times the algorithm will see the training data. One epoch is equals to one forward pass and one backward pass of all the training examples. Sometimes the model needs more epochs to properly learn.
    tensorboard_log_directory: "tensorboard" # This parameter enable files for tensorboard
    tensorboard_log_level: "epoch"
  - name: FallbackClassifier # The FallbackClassifier classifies a user message with the intent nlu_fallback in case the previous intent classifier wasn't able to classify an intent with a confidence greater or equal than the threshold of the FallbackClassifier.
    threshold: 0.4 
    ambiguity_threshold: 0.1 # The FallbackClassifier will also predict the nlu_fallback intent in case the difference of the confidence scores for the two highest ranked intents is smaller than the ambiguity_threshold.

policies: # Your assistant uses policies to decide which action to take at each step in a conversation. There are machine-learning and rule-based policies that your assistant can use in tandem.
  - name: MemoizationPolicy 
    max_history: 5
  - name: TEDPolicy # The Transformer Embedding Dialogue (TED) Policy is a multi-task architecture for next action prediction and entity recognition. The architecture several transformer encoders which are shared for both tasks.
    epochs: 200
    max_history: 5
  - name: RulePolicy # The RulePolicy is a policy that handles conversation parts that follow a fixed behavior (e.g. business logic).
    core_fallback_threshold: 0.3 
    core_fallback_action_name: action_default_fallback 
    enable_fallback_prediction: true
    restrict_rules: true
    check_for_contradictions: true 
    # For more information about pipeline componentes see: https://rasa.com/docs/rasa/components
    